import Link from 'next/link';
import ExperienceCard from '@/components/ExperienceCard';
import SoundtrackControl from '@/components/SoundtrackControl';
import VibConcierge from '@/components/VibConcierge';

export default function Home(){return <main className="wrap">
<section className="hero"><div><div className="eyebrow">A DAY IN LUXOR WITH THE PHARAOHS · DIGITAL TRAVEL COMPANION</div><h1>اعرف.<br/><span>اتأكد.</span><br/>اتحرك.</h1><p className="lead">مش مجرد دليل سياحي: مساعد رحلة يتعامل مع الموقف — من قبل الوصول، لحد آخر اليوم، ومعاك مسار بديل لو الخطة اتغيرت.</p><div className="actions"><Link className="btn" href="/visitor-center">مركز الزائر / Visitor Center</Link><Link className="btn alt" href="/vib">VIB Desk / Very Important Visitor</Link><Link className="btn alt" href="/what-can-i-do-now">ماذا أفعل الآن؟ / Start Now</Link></div><div className="trust"><b>✓ مصادر واضحة</b><b>✓ عربي + English</b><b>✓ بدون تسجيل إجباري</b><b>✓ خطة محلية بدون حساب</b></div></div><div className="seal"><img src="/logo.svg" alt="LUXOR PHARAOH DAY logo" width="220" height="220"/><h2>رحلتك لها نظام</h2><p>Discover · Check · Plan · Go · Adapt · Get Help</p><p>أجواء بصرية متحركة + صوت اختياري + خدمات VIB + خطط احتياطية، مع حدود ثقة واضحة.</p><SoundtrackControl/></div></section>
<VibConcierge/>
<section className="section"><h2>ماذا تحتاج؟</h2><p className="sub">لا تحتاج معرفة اسم الصفحة. ابدأ من الموقف الذي أنت فيه.</p><div className="grid"><ExperienceCard title="قبل الوصول" ar="Arrival" desc="جهز يومك واتصالك ونقطة البداية والميزانية." href="/visitor-guide#arrival"/><ExperienceCard title="أنا في الأقصر الآن" ar="Now" desc="حدد الوقت والاهتمامات والميزانية وخذ نقطة بداية." href="/what-can-i-do-now"/><ExperienceCard title="حصلت مشكلة" ar="Pharaoh Rescue" desc="خطة بديلة، سعر غير واضح، مكان مغلق، مشكلة نقل أو تحتاج دعمًا." href="/rescue"/></div></section>
<section className="section"><h2>الرحلة في مكان واحد</h2><div className="grid"><div className="card"><span className="tag">DISCOVER</span><h3>اكتشف</h3><p>المعالم والخيارات التي تناسب وقتك واهتماماتك.</p><Link className="btn alt" href="/experiences">Explore</Link></div><div className="card"><span className="tag">CHECK</span><h3>اتأكد</h3><p>السعر، المصدر، آخر مراجعة، وما يجب تأكيده قبل الشراء.</p><Link className="btn alt" href="/price-check">Price Check</Link></div><div className="card"><span className="tag">ADAPT</span><h3>اتصرف لو الخطة اتغيرت</h3><p>بدائل حسب الوقت، الميزانية، الموقع، والمجهود.</p><Link className="btn alt" href="/rescue">Pharaoh Rescue</Link></div><div className="card"><span className="tag">GO</span><h3>اتحرك</h3><p>خطوات تنقل عملية، ثم دعم وطوارئ عند الحاجة.</p><Link className="btn alt" href="/transport">Transport</Link></div></div></section>
<section className="section"><div className="hero-mini"><div><span className="tag">THE DIFFERENCE</span><h2>المنصة لا تسأل: «هتروح فين؟» فقط</h2><p>هي تسأل: «إنت محتاج إيه دلوقتي؟» ثم تبني المسار المناسب، وتقول بوضوح أين توجد معلومة مؤكدة وأين تحتاج تحقق.</p></div><div className="actions"><Link className="btn" href="/vib">اكتشف VIB</Link><Link className="btn alt" href="/trust">Trust & Transparency</Link></div></div></section>
<section className="section"><h2>قاعدة المنصة</h2><p className="sub">نغطي أكبر قدر عملي من احتياجات الزائر، لكن بدون اختراع بيانات أو تقديم خدمة منظمة قبل جاهزيتها القانونية والتشغيلية. كل جزء له مستوى ثقة واضح ومسار بديل عند نقص المعلومات.</p></section>
</main>}